name: CI

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow on

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2   
        
      - name: Install Dependencies
        working-directory: ./backend
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        working-directory: ./backend
        run: |
          source venv/bin/activate
          python -m pytest tests

      - name: Create archive of dependencies
        working-directory: ./backend
        run: |
          ls
          cd ./venv/lib/python3.10/site-packages
          ls
          zip -r9 ../../../../backend.zip .

      - name: Add ROUTERS files to Zip file
        working-directory: ./backend
        run:  | 
          cd ./routers && zip -g ../backend.zip -r .

      - name: Add DATA files to Zip file
        working-directory: ./backend
        run:  | 
          cd ./data && zip -g ../backend.zip -r .

      - name: Add DTOS files to Zip file
        working-directory: ./backend
        run:  | 
          cd ./dtos && zip -g ../backend.zip -r .

      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: ./backend/backend.zip

  frontend:
    runs-on: ubuntu-latest
    needs: backend  # This specifies that the frontend job depends on the successful completion of the backend job

    strategy:
      matrix:
        node-version: [18.13]  # Adjust the Node.js version as needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Angular CLI & build
        working-directory: ./frontend
        run: |
          npm install -g @angular/cli
          npm install 
          npm run build -- --configuration=production
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
         name: cloud_contacts_front_end  
         path: ./frontend
